BiSData["mage"] = {
    fire = {
        Head = {id = 207116, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Larodar, Keeper if the Flame"},
        Neck = {id = 195502, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Terros"},
        Shoulder = {id = 217234, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 217235, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Wrist = {id = 193510, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 193516, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Legs = {id = 217233, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Feet = {id = 207122, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Hands = {id = 217231, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 193731, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Halls of Infusion"},
        Trinket0 = {id = 212684, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Azure Vault"},
        Trinket1 = {id = 207172, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Tindral Sageswift"},
        MainHand = {id = 208616, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    },
    frost = {
        Head = {id = 207290, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Neck = {id = 207163, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Tindral Sageswift"},
        Shoulder = {id = 207288, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 202600, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Kazzara, the Hellforged"},
        Wrist = {id = 193510, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 193516, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Legs = {id = 207289, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Feet = {id = 207292, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst"},
        Hands = {id = 207291, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Finger0 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Finger1 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Trinket0 = {id = 194301, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "The Primal Council"},
        Trinket1 = {id = 212684, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Azure Vault"},
        MainHand = {id = 207790, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Larodar, Keeper of the Flame"},
        SecondaryHand = {id = 207796, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Urctos"}
    },
    arcane = {
        Head = {id = 217232, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Neck = {id = 210214, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Shoulder = {id = 217234, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 217235, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Wrist = {id = 193510, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 193516, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Legs = {id = 217233, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Feet = {id = 207292, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst"},
        Hands = {id = 217231, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Trinket0 = {id = 212684, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Azure Vault"},
        Trinket1 = {id = 193743, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Halls of Infusion"},
        MainHand = {id = 208616, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    }
}
