BiSData["shaman"] = {
    elemental = {
        Head = {id = 202591, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Warlord Kagni"},
        Neck = {id = 193001, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Shoulder = {id = 217240, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 217236, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Wrist = {id = 204704, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 207146, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Legs = {id = 217239, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Feet = {id = 193685, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "The Nokhud Offensive"},
        Hands = {id = 217237, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Finger0 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Finger1 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Trinket0 = {id = 212684, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Azure Vault"},
        Trinket1 = {id = 203729, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Neldris"},
        MainHand = {id = 207788, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Fyrakk"},
        SecondaryHand = {id = 195520, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"}
    },
    restoration = {
        Head = {id = 200399, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Neck = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Shoulder = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Back = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Chest = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Wrist = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Waist = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Legs = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Feet = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Hands = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Finger0 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Finger1 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Trinket0 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Trinket1 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        MainHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    },
    enhancement = {
        Head = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Neck = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Shoulder = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Back = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Chest = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Wrist = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Waist = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Legs = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Feet = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Hands = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Finger0 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Finger1 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Trinket0 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Trinket1 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        MainHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    }
}
