BiSData["warlock"] = {
    destruction = {
        Head = {id = 207116, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Larodar, Keeper of the Flame"},
        Neck = {id = 195502, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Terros"},
        Shoulder = {id = 217214, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Scalecommander Sarkareth"},
        Chest = {id = 217215, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Wrist = {id = 193510, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 202589, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Kazzara, the Hellforged"},
        Legs = {id = 217213, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Feet = {id = 193519, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Hands = {id = 217211, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Finger0 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Finger1 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Trinket0 = {id = 207172, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Tindral Sageswift"},
        Trinket1 = {id = 208615, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        MainHand = {id = 208616, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    },
    demonology = {
        Head = {id = 217212, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Neck = {id = 210214, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Shoulder = {id = 217214, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 217215, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Wrist = {id = 193510, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 193780, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Forgemaster Gorek"},
        Legs = {id = 217213, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Feet = {id = 193519, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Hands = {id = 193713, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Overgrown Ancient"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 193633, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Leymor"},
        Trinket0 = {id = 207172, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Tindral Sageswift"},
        Trinket1 = {id = 208615, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        MainHand = {id = 208616, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    },
    affliction = {
        Head = {id = 217212, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Neck = {id = 210214, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Shoulder = {id = 193667, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Gutshot"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 217215, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Wrist = {id = 193510, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 193780, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Forgemaster Gorek"},
        Legs = {id = 217213, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Feet = {id = 193519, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Hands = {id = 217211, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Catalyst, Raid or Great Vault"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Trinket0 = {id = 207172, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Tindral Sageswift"},
        Trinket1 = {id = 208615, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        MainHand = {id = 208616, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    }
}
