BiSData["paladin"] = {
    protection = {
        Head = {id = 217198, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Neck = {id = 202618, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Warlord Kagni"},
        Shoulder = {id = 217200, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 195494, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Dathea, Ascended"},
        Wrist = {id = 190502, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 190501, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Legs = {id = 217199, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Feet = {id = 204396, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Magmorax"},
        Hands = {id = 217197, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 201992, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Vault of the Incarnates BoE"},
        Trinket0 = {id = 202617, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Essence of Shadow"},
        Trinket1 = {id = 207166, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Smolderon"},
        MainHand = {id = 207786, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Fyrakk"},
        SecondaryHand = {id = 207797, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Gnarlroot"}
    },
    retribution = {
        Head = {id = 217198, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Neck = {id = 210214, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Shoulder = {id = 217200, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 195494, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Dathea, Ascended"},
        Wrist = {id = 190502, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 190501, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Legs = {id = 217199, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Feet = {id = 207148, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Hands = {id = 217197, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Trinket0 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        Trinket1 = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""},
        MainHand = {id = 206448, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Fyrakk"},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    },
    holy = {
        Head = {id = 193819, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Uldaman"},
        Neck = {id = 193001, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Shoulder = {id = 217200, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Back = {id = 202573, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Kazzara, the Hellforged"},
        Chest = {id = 217196, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Wrist = {id = 190526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 207149, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Larodar, Keeper of the Flame"},
        Legs = {id = 217199, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Feet = {id = 207148, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Hands = {id = 217197, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Finger0 = {id = 204398, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Neltharion"},
        Finger1 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Trinket0 = {id = 203729, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Forgotten Experiments"},
        Trinket1 = {id = 202612, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Kazzara, the Hellforged"},
        MainHand = {id = 207788, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Fyrakk"},
        SecondaryHand = {id = 202558, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Neltharion"}
    }
}
