BiSData["shaman"] = {
    elemental = {
        Head = {id = 202591, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Warlord Kagni"},
        Neck = {id = 193001, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Shoulder = {id = 217240, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 217236, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Wrist = {id = 204704, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 207146, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Volcoross"},
        Legs = {id = 217239, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Feet = {id = 193685, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "The Nokhud Offensive"},
        Hands = {id = 217237, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Finger0 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Finger1 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Trinket0 = {id = 212684, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Azure Vault"},
        Trinket1 = {id = 203729, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Neldris"},
        MainHand = {id = 207788, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Fyrakk"},
        SecondaryHand = {id = 195520, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"}
    },
    restoration = {
        Head = {id = 200399, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Neck = {id = 193001, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Shoulder = {id = 200401, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Back = {id = 207160, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Gnarlroot"},
        Chest = {id = 200396, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Wrist = {id = 204704, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 207144, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Gnarlroot"},
        Legs = {id = 200400, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Feet = {id = 207139, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Urctos"},
        Hands = {id = 200398, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 204398, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Neltharion"},
        Trinket0 = {id = 203729, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Neldris"},
        Trinket1 = {id = 202612, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Kazzara, the Hellforged"},
        MainHand = {id = 208616, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Nymue"},
        SecondaryHand = {id = 0, source = "wowhead", sourceset = "Overall BiS", dropsfrom = ""}
    },
    enhancement = {
        Head = {id = 217238, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Neck = {id = 207163, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Tindral Sageswift"},
        Shoulder = {id = 217240, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Back = {id = 204465, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Chest = {id = 217236, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Wrist = {id = 204704, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Waist = {id = 193425, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Crafted"},
        Legs = {id = 217239, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Raid/Catalyst"},
        Feet = {id = 204424, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Sarkareth"},
        Hands = {id = 193740, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Halls of Infusion"},
        Finger0 = {id = 195480, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Eranog"},
        Finger1 = {id = 195526, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Broodkeeper Diurna"},
        Trinket0 = {id = 203729, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Forgotten Experiments"},
        Trinket1 = {id = 207166, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Smolderon"},
        MainHand = {id = 207784, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Council of Dreams"},
        SecondaryHand = {id = 195512, source = "wowhead", sourceset = "Overall BiS", dropsfrom = "Kurog Grimtotem"}
    }
}
